#! /usr/bin/perl

use strict;
use warnings;

opendir DIR, ".";
my @readfiles 
    = grep { 
        /^[^\.]/          # Does not begin with a period
        && -f "$_"        # and is a file
	&& /CT$/       # and is this type
    } readdir(DIR);

close DIR;

my @files = sort{
    ($a =~ /T\.(-?\d{1,3}(\.\d{1,2})?)\.CT/)[0] <=> ($b =~ /T\.(-?\d{1,3}(\.\d{1,2})?)\.CT/)[0]
}@readfiles;

open FILE, ">index.dat";

print FILE "$#files\n";
foreach my $file (@files){
    print FILE "$file\n";
    if($file =~ /^T\.(-?\d{1,3}(\.\d{1,2})?)\.CT/){
	printf FILE "%.2f\n", $1;
    }
}

close FILE;
